name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout source code
       uses: actions/checkout@v1
     - name: Install Go
       uses: actions/setup-go@v1
       with:
        go-version: ${{ matrix.go-version }}
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
     - run: cd example && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip deployment.zip main
          
     - run: aws lambda update-function-code --function-name=crypto-goroutine-dev-crypto --zip-file=fileb://deployment.zip
          
          



          


