name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout source code
       uses: actions/checkout@v1
     - name: Install Go
       uses: actions/setup-go@v1
       with:
        go-version: ${{ matrix.go-version }}
     - name: Build binary
       run: |
          cd crypto && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip deployment.zip main

     - name: default deploy
       uses: appleboy/lambda-action@master
       with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: crypto-goroutine-dev-crypto
          zip_file: crypto/deployment.zip
          memory_size: 128
          timeout: 10
          runtime: nodejs12.x
     - run: aws lambda update-function-code --function-name=crypto-goroutine-dev-crypto --zip-file=fileb://crypto/deployment.zip







          


