name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout source code
       uses: actions/checkout@v1
     - name: Install Go
       uses: actions/setup-go@v1
       with:
        go-version: ${{ matrix.go-version }}
     - name: Build binary
       run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/crypto crypto/main.go && zip publish.zip bin/crypto
     - name: default deploy
       uses: appleboy/lambda-action@master
       with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: crypto-goroutine-dev-crypto
          


