name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout source code
       uses: actions/checkout@v1
     - name: Install Go
       uses: actions/setup-go@v1
       with:
        go-version: ${{ matrix.go-version }}
     - name: Build binary
       run: |
          cd crypto && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip deployment.zip main

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Deploy
        uses: 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          function-name: ${{ secrets.AWS_FUNCTION_NAME }}
          zip-file: crypto/deployment.zip






          


